--[[   Service dependencies   --]]
local RS = game:GetService("ReplicatedStorage");

--[[   Folder references   --]]
local TBCFolder = RS.TurnBasedCombat;
local moduleFolder = TBCFolder.Modules;
local classesFolder = TBCFolder.Classes;
local miscFolder = RS.Misc;

--[[   External dependencies   --]]
local util = require(miscFolder.Util);
local enemyDatabase = require(classesFolder.PartyMember.EnemyPartyMember.Storage.EnemyNPCList);
local plrDebuffsList = require(classesFolder.Buff.Storage.PlayerDebuffsList);
local enemyBuffsList = require(classesFolder.Buff.Storage.EnemyBuffsList);

--[[   Class dependencies   --]]
local Action = require(classesFolder.Action);
local EnemyAction = require(classesFolder.Action.EnemyAction);


--[[   Key variables   --]]





--[[
EnemyAction(String actionName, String description, String logFlavor, bool noExtraLineNeeded, bool mentionTarget, String playerOrEnemyParty, String targetType, String speedPriority,
	   		int hpCost, bool canUseIfBinded, int damageMultiplier, int accuracy, String imbuedElement, String damageType,
	   		int hpHealingAmount, String[] buffs, int critRateModifier, bool isRevivalSkill, float damageWaitDelay, bool isSupportSpell)

NOTES:
String targetType can be: SELF, SINGLEPARTY, SINGLEENEMY, ALLPARTY, ALLENEMY, SPLASHPARTY, SPLASHENEMY, NONE
String speedPriority can be: GOFIRST, NONE, or GOLAST
String imbuedElement can be: WEAPON, PYRO, CRYO, ELECTRO, NONE
String damageType can be: SLASH, CRUSH, STAB, WEAPON, NONE
String[] buffs singular element can be: PATK/MATK(INCREASEAMOUNT), PDEF/MDEF(INCREASEAMOUNT), SPD(INCREASEAMOUNT), EVA(INCREASEPERCENTAGE)
int critRateModifier is in percent
--]]

--local EnemyActionsList = {
--	["Attack"] = EnemyAction("Attack", "Attacks a single target.", "attacks!", false, false, "PlayerParty", "SINGLEPARTY", "NONE",
--		0, false, 100, 100, "WEAPON", "WEAPON",
--		0, nil, 0, false, 0, false),
--	["Defend"] = EnemyAction("Defend", "Goes into defensive form to take reduced damage.", "defends.", true, true, "EnemyParty", "SELF", "GOFIRST",
--		0, false, 0, math.huge, "NONE", "NONE",
--		0, nil, 0, false, 0, false),
--	["Flight"] = EnemyAction("Flight", "Attempts to escape from battle.", "resorts to flight!", false, false, "EnemyParty", "SELF", "NONE",
--		0, 0, false, math.huge, "NONE", "NONE",
--		0, nil, 0, false, 0, false),
--	["Stare"] = EnemyAction("Stare", "Does nothing!", "stares intently.", true, false, "PlayerParty", "NONE", "NONE",
--		0, true, 0, math.huge, "NONE", "NONE",
--		0, nil, 0, false, 0, false),
--	["Rolling Rampage"] = EnemyAction("Rolling Rampage", "Attempts to roll over the enemy party.", "goes on a rolling rampage!", false, false, "PlayerParty", "ALLPARTY", "NONE",
--		Random.new():NextInteger(15,30), false, 150, 70, "WEAPON", "CRUSH",
--		0, nil, 30, false, .45, false),
--	["Desperate Attack"] = EnemyAction("Desperate Attack", "Strikes desperately.", "makes a desperate attack!", false, false, "PlayerParty", "SINGLEPARTY", "NONE",
--		0, false, 250, 50, "WEAPON", "WEAPON",
--		0, nil, 100, false, 0, false),
--	["Radish Bomb"] = EnemyAction("Radish Bomb", "Spits out a radish bomb to deal splash DMG.", "spits out a radish bomb!", false, false, "PlayerParty", "SPLASHPARTY", "NONE",
--		0, false, 310, 95, "WEAPON", "CRUSH",
--		0, nil, 0, false, 0, false),
--	["Call for Help"] = EnemyAction("Call for Help", "Calls for another's monster to join the battle.", "calls for help!", false, false, "EnemyParty", "NONE", "NONE",
--		0, true, 0, math.huge, "NONE", "NONE",
--		0, nil, 0, false, 0, false),
--};

--WIP
local EnemyActionsList = {
	["Attack"] = {
		['NAME'] = 'Attack',
		['DESCRIPTION'] = 'Attacks a single target.',
		['LOGFLAVOR'] = 'attacks!',
		['NOEXTRALINENEEDED'] = false,
		['MENTIONTARGET'] = false,
		['PLAYERORENEMYPARTY'] = 'PlayerParty',
		['TARGETTYPE'] = 'SINGLEPARTY',
		['SPEEDPRIORITY'] = 'NONE',
		['HPCOST'] = 0,
		['CANUSEIFBINDED'] = false,
		['DAMAGEMULTIPLIER'] = 100,
		['ACCURACY'] = 100,
		['IMBUEDELEMENT'] = 'WEAPON',
		['DAMAGETYPE'] = 'WEAPON',
		['HPHEALINGAMOUNT'] = 0,
		['CRITRATEMODIFIER'] = 20,
		['ISREVIVALSKILL'] = false,
		['DAMAGEWAITDELAY'] = 0,
		['ISSUPPORTSPELL'] = false,
	},
	["Defend"] = {
		['NAME'] = 'Defend',
		['DESCRIPTION'] = 'Goes into defensive form to take reduced damage.',
		['LOGFLAVOR'] = 'is defending.',
		['NOEXTRALINENEEDED'] = true,
		['MENTIONTARGET'] = false,
		['PLAYERORENEMYPARTY'] = 'EnemyParty',
		['TARGETTYPE'] = 'SELF',
		['SPEEDPRIORITY'] = 'GOFIRST',
		['HPCOST'] = 0,
		['CANUSEIFBINDED'] = false,
		['DAMAGEMULTIPLIER'] = 0,
		['ACCURACY'] = math.huge,
		['IMBUEDELEMENT'] = 'NONE',
		['DAMAGETYPE'] = 'NONE',
		['HPHEALINGAMOUNT'] = 0,
		['CRITRATEMODIFIER'] = 0,
		['ISREVIVALSKILL'] = false,
		['DAMAGEWAITDELAY'] = 0,
		['ISSUPPORTSPELL'] = true,
	},
	["Flight"] = {
		['NAME'] = 'Flight',
		['DESCRIPTION'] = 'Attempts to escape from battle.',
		['LOGFLAVOR'] = 'resorts to flight!',
		['NOEXTRALINENEEDED'] = false,
		['MENTIONTARGET'] = false,
		['PLAYERORENEMYPARTY'] = 'EnemyParty',
		['TARGETTYPE'] = 'SELF',
		['SPEEDPRIORITY'] = 'NONE',
		['HPCOST'] = 0,
		['CANUSEIFBINDED'] = false,
		['DAMAGEMULTIPLIER'] = 0,
		['ACCURACY'] = math.huge,
		['IMBUEDELEMENT'] = 'NONE',
		['DAMAGETYPE'] = 'NONE',
		['HPHEALINGAMOUNT'] = 0,
		['CRITRATEMODIFIER'] = 0,
		['ISREVIVALSKILL'] = false,
		['DAMAGEWAITDELAY'] = 0,
		['ISSUPPORTSPELL'] = false,
	},	
	["Stare"] = {
		['NAME'] = 'Stare',
		['DESCRIPTION'] = 'Does nothing!',
		['LOGFLAVOR'] = 'stares intently.',
		['NOEXTRALINENEEDED'] = true,
		['MENTIONTARGET'] = false,
		['PLAYERORENEMYPARTY'] = 'EnemyParty',
		['TARGETTYPE'] = 'NONE',
		['SPEEDPRIORITY'] = 'NONE',
		['HPCOST'] = 0,
		['CANUSEIFBINDED'] = true,
		['DAMAGEMULTIPLIER'] = 0,
		['ACCURACY'] = math.huge,
		['IMBUEDELEMENT'] = 'NONE',
		['DAMAGETYPE'] = 'NONE',
		['HPHEALINGAMOUNT'] = 0,
		['CRITRATEMODIFIER'] = 0,
		['ISREVIVALSKILL'] = false,
		['DAMAGEWAITDELAY'] = 0,
		['ISSUPPORTSPELL'] = false,
	},	
	["Rolling Rampage"] = {
		['NAME'] = 'Rolling Rampage',
		['DESCRIPTION'] = 'Recklessly barrel rolls the entire party.',
		['LOGFLAVOR'] = 'goes on a rolling rampage!',
		['NOEXTRALINENEEDED'] = false,
		['MENTIONTARGET'] = false,
		['PLAYERORENEMYPARTY'] = 'PlayerParty',
		['TARGETTYPE'] = 'ALLPARTY',
		['SPEEDPRIORITY'] = 'NONE',
		['HPCOST'] = math.floor(enemyDatabase['Radical Radish']['HP'] / 2),
		['CANUSEIFBINDED'] = false,
		['DAMAGEMULTIPLIER'] = 175,
		['ACCURACY'] = 65,
		['IMBUEDELEMENT'] = 'WEAPON',
		['DAMAGETYPE'] = 'CRUSH',
		['HPHEALINGAMOUNT'] = 0,
		['CRITRATEMODIFIER'] = 50,
		['ISREVIVALSKILL'] = false,
		['DAMAGEWAITDELAY'] = .35,
		['ISSUPPORTSPELL'] = false,
	},	
	["Desperate Attack"] = {
		['NAME'] = 'Desperate Attack',
		['DESCRIPTION'] = 'Strikes desperately at a single target.',
		['LOGFLAVOR'] = 'makes a desperate attack!',
		['NOEXTRALINENEEDED'] = false,
		['MENTIONTARGET'] = false,
		['PLAYERORENEMYPARTY'] = 'PlayerParty',
		['TARGETTYPE'] = 'SINGLEPARTY',
		['SPEEDPRIORITY'] = 'NONE',
		['HPCOST'] = 0,
		['CANUSEIFBINDED'] = false,
		['DAMAGEMULTIPLIER'] = 250,
		['ACCURACY'] = 50,
		['IMBUEDELEMENT'] = 'WEAPON',
		['DAMAGETYPE'] = 'WEAPON',
		['HPHEALINGAMOUNT'] = 0,
		['CRITRATEMODIFIER'] = 100,
		['ISREVIVALSKILL'] = false,
		['DAMAGEWAITDELAY'] = 0,
		['ISSUPPORTSPELL'] = false,
	},	
	["Birb Pounce"] = {
		['NAME'] = 'Birb Pounce',
		['DESCRIPTION'] = 'Deals splash crush damage.',
		['LOGFLAVOR'] = 'flies up into the air and makes a sky drop!',
		['NOEXTRALINENEEDED'] = false,
		['MENTIONTARGET'] = false,
		['PLAYERORENEMYPARTY'] = 'PlayerParty',
		['TARGETTYPE'] = 'SPLASHPARTY',
		['SPEEDPRIORITY'] = 'NONE',
		['HPCOST'] = 0,
		['CANUSEIFBINDED'] = false,
		['DAMAGEMULTIPLIER'] = 150,
		['ACCURACY'] = 80,
		['IMBUEDELEMENT'] = 'WEAPON',
		['DAMAGETYPE'] = 'CRUSH',
		['HPHEALINGAMOUNT'] = 0,
		['CRITRATEMODIFIER'] = 5,
		['ISREVIVALSKILL'] = false,
		['DAMAGEWAITDELAY'] = 0,
		['ISSUPPORTSPELL'] = false,
	},	
	["Slack Off"] = {
		['NAME'] = 'Slack Off',
		['DESCRIPTION'] = 'Recovers some hp.',
		['LOGFLAVOR'] = 'is slacking off.',
		['NOEXTRALINENEEDED'] = false,
		['MENTIONTARGET'] = false,
		['PLAYERORENEMYPARTY'] = 'PlayerParty',
		['TARGETTYPE'] = 'SELF',
		['SPEEDPRIORITY'] = 'NONE',
		['HPCOST'] = 0,
		['CANUSEIFBINDED'] = true,
		['DAMAGEMULTIPLIER'] = -125,
		['ACCURACY'] = math.huge,
		['IMBUEDELEMENT'] = 'NONE',
		['DAMAGETYPE'] = 'NONE',
		['HPHEALINGAMOUNT'] = 0,
		['CRITRATEMODIFIER'] = 0,
		['ISREVIVALSKILL'] = false,
		['DAMAGEWAITDELAY'] = 0,
		['ISSUPPORTSPELL'] = false,
	},	
	["Call for Help"] = {
		['NAME'] = 'Call for Help',
		['DESCRIPTION'] = 'Calls for another monster to join the fray.',
		['LOGFLAVOR'] = 'calls for help!',
		['NOEXTRALINENEEDED'] = false,
		['MENTIONTARGET'] = false,
		['PLAYERORENEMYPARTY'] = 'EnemyParty',
		['TARGETTYPE'] = 'NONE',
		['SPEEDPRIORITY'] = 'NONE',
		['HPCOST'] = 0,
		['CANUSEIFBINDED'] = true,
		['DAMAGEMULTIPLIER'] = 0,
		['ACCURACY'] = math.huge,
		['IMBUEDELEMENT'] = 'NONE',
		['DAMAGETYPE'] = 'NONE',
		['HPHEALINGAMOUNT'] = 0,
		['CRITRATEMODIFIER'] = 0,
		['ISREVIVALSKILL'] = false,
		['DAMAGEWAITDELAY'] = 0,
		['ISSUPPORTSPELL'] = false,
	},	
	["Poison Fart"] = {
		['NAME'] = 'Poison Fart',
		['DESCRIPTION'] = 'Farts poison gas!.',
		['LOGFLAVOR'] = 'farts poison gas!',
		['NOEXTRALINENEEDED'] = false,
		['MENTIONTARGET'] = false,
		['PLAYERORENEMYPARTY'] = 'PlayerParty',
		['TARGETTYPE'] = 'ALLPARTY',
		['SPEEDPRIORITY'] = 'NONE',
		['HPCOST'] = 0,
		['CANUSEIFBINDED'] = true,
		['DAMAGEMULTIPLIER'] = 50,
		['ACCURACY'] = 95,
		['IMBUEDELEMENT'] = 'NONE',
		['DAMAGETYPE'] = 'NONE',
		['HPHEALINGAMOUNT'] = 0,
		['CRITRATEMODIFIER'] = -100,
		['ISREVIVALSKILL'] = false,
		['DAMAGEWAITDELAY'] = 0,
		['ISSUPPORTSPELL'] = false,
		['STATUSEFFECT'] = "POISONED@70",
		['MINSTATUSEFFECTDURATION'] = 2,
		['MAXSTATUSEFFECTDURATION'] = 4,
	},	
	["Bite"] = {
		['NAME'] = 'Bite',
		['DESCRIPTION'] = 'Bites the target.',
		['LOGFLAVOR'] = 'widens its jaws and bites down!',
		['NOEXTRALINENEEDED'] = false,
		['MENTIONTARGET'] = false,
		['PLAYERORENEMYPARTY'] = 'PlayerParty',
		['TARGETTYPE'] = 'SINGLEPARTY',
		['SPEEDPRIORITY'] = 'NONE',
		['HPCOST'] = -30,
		['CANUSEIFBINDED'] = true,
		['DAMAGEMULTIPLIER'] = 130,
		['ACCURACY'] = 95,
		['IMBUEDELEMENT'] = 'NONE',
		['DAMAGETYPE'] = 'CRUSH',
		['HPHEALINGAMOUNT'] = 0,
		['CRITRATEMODIFIER'] = 35,
		['ISREVIVALSKILL'] = false,
		['DAMAGEWAITDELAY'] = 0,
		['ISSUPPORTSPELL'] = false,
		['STATUSEFFECT'] = "BLEEDING@60",
		['MINSTATUSEFFECTDURATION'] = 2,
		['MAXSTATUSEFFECTDURATION'] = 4,
	},	
	["Rot"] = {
		['NAME'] = 'Rot',
		['DESCRIPTION'] = 'Kills itself, unleashing nasty bacteria.',
		['LOGFLAVOR'] = 'crushes its own head, unleashing a fume that carries a deadly disease!',
		['NOEXTRALINENEEDED'] = false,
		['MENTIONTARGET'] = false,
		['PLAYERORENEMYPARTY'] = 'PlayerParty',
		['TARGETTYPE'] = 'ALLPARTY',
		['SPEEDPRIORITY'] = 'NONE',
		['HPCOST'] = 100,
		['CANUSEIFBINDED'] = true,
		['DAMAGEMULTIPLIER'] = 25,
		['ACCURACY'] = 50,
		['IMBUEDELEMENT'] = 'NONE',
		['DAMAGETYPE'] = 'NONE',
		['HPHEALINGAMOUNT'] = 0,
		['CRITRATEMODIFIER'] = -100,
		['ISREVIVALSKILL'] = false,
		['DAMAGEWAITDELAY'] = 0,
		['ISSUPPORTSPELL'] = false,
		['STATUSEFFECT'] = "PLAGUE@100",
		['MINSTATUSEFFECTDURATION'] = 4,
		['MAXSTATUSEFFECTDURATION'] = 6,
	},	
	["Flamethrower"] = {
		['NAME'] = 'Flamethrower',
		['DESCRIPTION'] = 'spews out a fiery inferno.',
		['LOGFLAVOR'] = 'spews out a fiery inferno!',
		['NOEXTRALINENEEDED'] = false,
		['MENTIONTARGET'] = false,
		['PLAYERORENEMYPARTY'] = 'PlayerParty',
		['TARGETTYPE'] = 'ALLPARTY',
		['SPEEDPRIORITY'] = 'NONE',
		['HPCOST'] = 0,
		['CANUSEIFBINDED'] = true,
		['DAMAGEMULTIPLIER'] = 200,
		['ACCURACY'] = 95,
		['IMBUEDELEMENT'] = 'PYRO',
		['DAMAGETYPE'] = 'NONE',
		['HPHEALINGAMOUNT'] = 0,
		['CRITRATEMODIFIER'] = -100,
		['ISREVIVALSKILL'] = false,
		['DAMAGEWAITDELAY'] = 0,
		['ISSUPPORTSPELL'] = false,
		['STATUSEFFECT'] = "BURNED@100",
		['MINSTATUSEFFECTDURATION'] = 3,
		['MAXSTATUSEFFECTDURATION'] = 4,
	},	
	["Reckless Charge"] = {
		['NAME'] = 'Reckless Charge',
		['DESCRIPTION'] = 'Recklessly charges, dealing splash damage and recoil damage.',
		['LOGFLAVOR'] = 'suddenly charges recklessly!',
		['NOEXTRALINENEEDED'] = false,
		['MENTIONTARGET'] = false,
		['PLAYERORENEMYPARTY'] = 'PlayerParty',
		['TARGETTYPE'] = 'ALLPARTY',
		['SPEEDPRIORITY'] = 'NONE',
		['HPCOST'] = math.floor(enemyDatabase['Chonk Birb Lord']['HP'] / 16),
		['CANUSEIFBINDED'] = false,
		['DAMAGEMULTIPLIER'] = 165,
		['ACCURACY'] = 45,
		['IMBUEDELEMENT'] = 'WEAPON',
		['DAMAGETYPE'] = 'CRUSH',
		['HPHEALINGAMOUNT'] = 0,
		['CRITRATEMODIFIER'] = 50,
		['ISREVIVALSKILL'] = false,
		['DAMAGEWAITDELAY'] = .20,
		['ISSUPPORTSPELL'] = false,
	},	
	["Volt Tackle"] = {
		['NAME'] = 'Volt Tackle',
		['DESCRIPTION'] = 'Imbues itself in electricity, tackling the target',
		['LOGFLAVOR'] = 'Imbues itself in electricity and charges!',
		['NOEXTRALINENEEDED'] = false,
		['MENTIONTARGET'] = false,
		['PLAYERORENEMYPARTY'] = 'PlayerParty',
		['TARGETTYPE'] = 'SINGLEPARTY',
		['SPEEDPRIORITY'] = 'NONE',
		['HPCOST'] = math.floor(enemyDatabase['Chonk Birb Lord']['HP'] / 26),
		['CANUSEIFBINDED'] = false,
		['DAMAGEMULTIPLIER'] = 270,
		['ACCURACY'] = 75,
		['IMBUEDELEMENT'] = 'ELECTRO',
		['DAMAGETYPE'] = 'CRUSH',
		['HPHEALINGAMOUNT'] = 0,
		['CRITRATEMODIFIER'] = 65,
		['ISREVIVALSKILL'] = false,
		['DAMAGEWAITDELAY'] = 0,
		['ISSUPPORTSPELL'] = false,
	},
	["Intimidate"] = {
		['NAME'] = 'Intimidate',
		['DESCRIPTION'] = 'Intimidates all targets, reducing their ATK and SPD by 35% for 3 turns.',
		['LOGFLAVOR'] = 'Lets out a predatory cry!',
		['NOEXTRALINENEEDED'] = false,
		['MENTIONTARGET'] = false,
		['PLAYERORENEMYPARTY'] = 'PlayerParty',
		['TARGETTYPE'] = 'ALLPARTY',
		['SPEEDPRIORITY'] = 'NONE',
		['HPCOST'] = 0,
		['CANUSEIFBINDED'] = false,
		['DAMAGEMULTIPLIER'] = 270,
		['ACCURACY'] = 75,
		['IMBUEDELEMENT'] = 'NONE',
		['DAMAGETYPE'] = 'EFFECT',
		['HPHEALINGAMOUNT'] = 0,
		['CRITRATEMODIFIER'] = 0,
		['ISREVIVALSKILL'] = false,
		['DAMAGEWAITDELAY'] = 0,
		['ISSUPPORTSPELL'] = true,
		['DEBUFFS'] = plrDebuffsList['Intimidate'],
		['DEBUFFSDURATION'] = 3,
		['SUPPORTSPELLFLAVOR'] = "'s attack and speed decreased moderately!",
	},	
	
	
};

return EnemyActionsList;


